spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-cart
  thymeleaf:
    cache: false
  redis:
    host: 192.168.59.10
server:
  port: 10003
  #开启feign对sentinel的支持
  feign:
    sentinel:
      enabled: true


    session:
      store-type: redis
    #配置线程池

mall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
