spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-cart
  thymeleaf:
    cache: false
  redis:
    host: 192.168.255.128
server:
  port: 10003
