
spring:
  datasource:
    username: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.255.128:3306/mall_stock?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-stock
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 10011
logging:
  level:
    com.example.mall: debug

#Alibaba OSS配置
#alibaba:
#  cloud:
#    access-key: LTAI5t8Mniv4n3hanc6oonRi
#    secret-key: NemsnmjkrR7e4pMA0uFJHbBCp14SeE
#    oss:
#      endpoint: oss-cn-beijing.aliyuncs.com

